# Generated by Django 4.2.1 on 2023-09-12 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uzivatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'uživatel',
                'verbose_name_plural': 'uživatelé',
            },
        ),
        migrations.CreateModel(
            name='Pojisteni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_pojisteni', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Pojištění',
                'verbose_name_plural': 'Pojištění',
            },
        ),
        migrations.CreateModel(
            name='PojisteniPojisteny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.IntegerField(default=0)),
                ('predmet_pojisteni', models.CharField(max_length=100)),
                ('platnost_od', models.DateTimeField()),
                ('platnost_do', models.DateTimeField()),
                ('pojisteni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pojisteni_app.pojisteni')),
            ],
            options={
                'verbose_name': 'Pojištěný - Pojištění',
                'verbose_name_plural': 'Pojištěný - Pojištění',
            },
        ),
        migrations.CreateModel(
            name='Pojisteny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
                ('prijmeni', models.CharField(max_length=100)),
                ('ulice', models.CharField(max_length=200)),
                ('mesto', models.CharField(max_length=200)),
                ('psc', models.IntegerField(default=0)),
                ('tel', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=180)),
                ('pojisteni', models.ManyToManyField(through='pojisteni_app.PojisteniPojisteny', to='pojisteni_app.pojisteni')),
            ],
            options={
                'verbose_name': 'Pojištěný',
                'verbose_name_plural': 'Pojištěnci',
            },
        ),
        migrations.AddField(
            model_name='pojistenipojisteny',
            name='pojisteny',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pojisteni_app.pojisteny'),
        ),
    ]
