# Generated by Django 4.2.1 on 2023-09-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni_app', '0002_udalosti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojisteny',
            name='tel',
            field=models.CharField(max_length=15),
        ),
    ]
